/**
 * Barrel export for all Nous-OSS interface contracts.
 */
export type { IPfcEngine, ICoreExecutor } from './cortex.js';
export type {
  IStmStore,
  ILtmStore,
  IDistillationEngine,
  IRetrievalEngine,
  IKnowledgeIndex,
  IAccessPolicy,
  IMemoryAccessPolicyEngine,
} from './memory.js';
export type {
  IModelRouter,
  IModelProvider,
  CliSessionContext,
  TeardownScope,
  ICliSessionManager,
  IToolExecutor,
  WorkflowStartRequest,
  IWorkflowEngine,
  IProjectStore,
  ITaskStore,
  IArtifactStore,
  IScheduler,
  IEscalationService,
  INotificationService,
  IRegistryService,
  INudgeDiscoveryService,
  ICommunicationGatewayService,
  ExternalSourceCommandContext,
  ExternalSourceCompactCommand,
  ExternalSourceDeleteCommand,
  ExternalSourceGetQuery,
  ExternalSourcePutCommand,
  ExternalSourceSearchQuery,
  IExternalSourceMemoryService,
  IPromotedMemoryBridgeService,
  IPublicMcpDeploymentRouterService,
  IPublicMcpGatewayService,
  IPublicMcpSurfaceService,
  IEndpointTrustService,
  IVoiceControlService,
  ISandbox,
  IAppCredentialInstallService,
  IAppInstallService,
  IAppSettingsService,
  IAppRuntimeService,
  IPackageLifecycleOrchestrator,
  IPackageInstallService,
  ISkillAdmissionOrchestrator,
  IWitnessService,
  IOpctlService,
  IMaoProjectionService,
  IGtmGateCalculator,
  PublicMcpAgentInvokeCommand,
  PublicMcpAgentListQuery,
  PublicMcpSystemInfoQuery,
  PublicMcpTaskQuery,
} from './subcortex.js';
export type {
  IProjectApiMemory,
  IProjectApiModel,
  IProjectApiTool,
  IProjectApiArtifact,
  IProjectApiEscalation,
  IProjectApiScheduler,
  IProjectApiProject,
  IProjectApi,
} from './project-api.js';
export type {
  IWorkmodeRegistry,
  IWorkmodeAdmissionGuard,
  ILeaseStore,
  AuthorityActor,
  DispatchAdmissionInput,
  LifecycleAdmissionInput,
  ScopeGuardExecutionContext,
} from './workmode.js';
export type {
  IChatScopeResolver,
  IChatIntentClassifier,
  IChatControlRouter,
  IChatThreadStore,
  IChatThreadBindGuard,
} from './chat.js';
export type {
  IAgentGateway,
  IAgentGatewayFactory,
  IGatewayInboxHandle,
  IGatewayLifecycleHooks,
  IGatewayOutboxSink,
  IScopedMcpToolSurface,
  AgentGatewayConfig,
  GatewayLifecycleContext,
  GatewayTaskCompletionHookResult,
  // WR-127 strategy injection types
  HarnessStrategies,
  PromptFormatter,
  PromptFormatterInput,
  PromptFormatterOutput,
  ResponseParser,
  ContextDefaults,
  ContextStrategy,
  LoopConfig,
  ToolConcurrencyConfig,
  // WR-128 / SP 1.2 personality structural mirror
  PersonalityPreset,
  PersonalityConfig,
  TraitAxes,
} from './agent-gateway.js';
export type {
  IIngressTriggerValidator,
  IIngressAuthnVerifier,
  IIngressAuthzEvaluator,
  IIngressIdempotencyStore,
  IIngressDispatchAdmission,
  IIngressGateway,
  IngressValidationResult,
  IngressAuthnResult,
  IngressAuthzResult,
  IngressIdempotencyClaimResult,
  IngressIdempotencyCheckResult,
} from './ingress.js';
export type {
  IRecoveryLedgerStore,
  ICheckpointManager,
  IRetryPolicyEvaluator,
  IRollbackPolicyEvaluator,
  IRecoveryOrchestrator,
  RetryPolicyResult,
  RollbackPolicyResult,
  RecoveryCriticalEvent,
  AppendResult,
  SealResult,
  CheckpointSnapshot,
  PrepareResult,
  CommitResult,
  ChainValidationResult,
  RetryEvaluationContext,
  RollbackEvaluationContext,
  RecoveryOrchestratorContext,
} from './recovery.js';
export type { IThoughtEmitter } from './thought-emitter.js';
export type {
  IDocumentStore,
  IVectorStore,
  IGraphStore,
  IEmbedder,
  IRuntime,
  IConfig,
  IHealthMonitor,
  IGatewayHealthSource,
  IProviderHealthSource,
  IHealthAggregator,
  ICredentialVaultService,
  ICredentialInjector,
  SystemConfig,
  AgentUserProfile,
} from './autonomic.js';
export type {
  ILogChannel,
  ILogEgress,
  ILogger,
} from './logging.js';
