import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const generatorScript = join(packageRoot, 'scripts', 'generate-provider-aggregates.mjs');
const generatedRoot = join(packageRoot, 'src', 'generated');
const providersRoot = join(packageRoot, 'src', 'providers');

describe('provider aggregate codegen', () => {
  it('discovers certified provider leaves in deterministic vendor order', () => {
    const output = execFileSync(
      process.execPath,
      [generatorScript, '--list', '--check'],
      { cwd: packageRoot, encoding: 'utf8' },
    )
      .trim()
      .split(/\r?\n/);

    expect(output).toEqual(['anthropic', 'codex-cli', 'ollama', 'openai']);
  });

  it('keeps checked-in generated files in sync with provider leaves', () => {
    expect(() => execFileSync(
      process.execPath,
      [generatorScript, '--check'],
      { cwd: packageRoot, stdio: 'pipe' },
    )).not.toThrow();
  });

  it('rejects numeric-leading provider leaves before generating invalid TypeScript aliases', () => {
    const invalidProviderRoot = join(providersRoot, '3p-provider');

    try {
      rmSync(invalidProviderRoot, { recursive: true, force: true });
      mkdirSync(invalidProviderRoot);

      expect(() => execFileSync(
        process.execPath,
        [generatorScript, '--list'],
        { cwd: packageRoot, encoding: 'utf8', stdio: 'pipe' },
      )).toThrow(/Use lowercase ASCII kebab-case starting with a letter/);
    } finally {
      rmSync(invalidProviderRoot, { recursive: true, force: true });
    }
  });

  it('emits generated aggregates that import through provider leaves only', () => {
    const generatedFiles = existsSync(generatedRoot)
      ? readdirSync(generatedRoot)
        .filter((fileName) => fileName.endsWith('.generated.ts'))
        .sort()
      : [];

    expect(generatedFiles).toEqual([]);

    for (const fileName of [
      'provider-adapters.ts',
      'provider-definitions.ts',
      'provider-factories.ts',
    ]) {
      const source = readFileSync(join(packageRoot, 'src', fileName), 'utf8');
      expect(source.startsWith('// @generated by scripts/generate-provider-aggregates.mjs; do not edit by hand.\n')).toBe(true);
      expect(source).toContain('./providers/');
      expect(source).toContain('./schemas/');
      expect(source).not.toContain('./generated/provider-');
    }

    const adapterSource = readFileSync(join(packageRoot, 'src', 'provider-adapters.ts'), 'utf8');
    expect(adapterSource).toContain('CERTIFIED_PROVIDER_ADAPTER_MODULES');
    expect(adapterSource).toContain('CertifiedProviderAdapterKey');
  });
});
