// @generated by scripts/generate-provider-aggregates.mjs; do not edit by hand.
import type { ProviderAdapterModule } from './schemas/provider-adapter.js';
import { providerAdapter as anthropicProviderAdapter } from './providers/anthropic/adapter.js';
import { providerAdapter as codexCliProviderAdapter } from './providers/codex-cli/adapter.js';
import { providerAdapter as deepinfraProviderAdapter } from './providers/deepinfra/adapter.js';
import { providerAdapter as githubCopilotCliProviderAdapter } from './providers/github-copilot-cli/adapter.js';
import { providerAdapter as groqProviderAdapter } from './providers/groq/adapter.js';
import { providerAdapter as llamaCppProviderAdapter } from './providers/llama-cpp/adapter.js';
import { providerAdapter as moonshotProviderAdapter } from './providers/moonshot/adapter.js';
import { providerAdapter as ollamaProviderAdapter } from './providers/ollama/adapter.js';
import { providerAdapter as openaiProviderAdapter } from './providers/openai/adapter.js';
import { providerAdapter as openclawProviderAdapter } from './providers/openclaw/adapter.js';
import { providerAdapter as openrouterProviderAdapter } from './providers/openrouter/adapter.js';
import { providerAdapter as perplexityProviderAdapter } from './providers/perplexity/adapter.js';

export * from './schemas/provider-adapter.js';
export { providerAdapter as anthropicAdapter, createAnthropicAdapter } from './providers/anthropic/adapter.js';
export { providerAdapter as codexCliAdapter, CODEX_CLI_EXECUTION_CAPABILITY_PROFILE, createCodexCliAdapter, renderCodexCliPrompt } from './providers/codex-cli/adapter.js';
export { providerAdapter as deepinfraAdapter } from './providers/deepinfra/adapter.js';
export { providerAdapter as githubCopilotCliAdapter } from './providers/github-copilot-cli/adapter.js';
export { providerAdapter as groqAdapter } from './providers/groq/adapter.js';
export { providerAdapter as llamaCppAdapter } from './providers/llama-cpp/adapter.js';
export { providerAdapter as moonshotAdapter } from './providers/moonshot/adapter.js';
export { providerAdapter as ollamaAdapter, createOllamaAdapter, isToolCapableModel } from './providers/ollama/adapter.js';
export { providerAdapter as openaiAdapter, createChatCompletionsAdapter } from './providers/openai/adapter.js';
export { providerAdapter as openclawAdapter, OPENCLAW_EXECUTION_CAPABILITY_PROFILE, createOpenClawAdapter, renderOpenClawPrompt } from './providers/openclaw/adapter.js';
export { providerAdapter as openrouterAdapter } from './providers/openrouter/adapter.js';
export { providerAdapter as perplexityAdapter } from './providers/perplexity/adapter.js';

export const CERTIFIED_PROVIDER_ADAPTER_MODULES = [
  anthropicProviderAdapter,
  codexCliProviderAdapter,
  deepinfraProviderAdapter,
  githubCopilotCliProviderAdapter,
  groqProviderAdapter,
  llamaCppProviderAdapter,
  moonshotProviderAdapter,
  ollamaProviderAdapter,
  openaiProviderAdapter,
  openclawProviderAdapter,
  openrouterProviderAdapter,
  perplexityProviderAdapter,
] as const satisfies readonly ProviderAdapterModule[];

export type CertifiedProviderAdapterKey =
  (typeof CERTIFIED_PROVIDER_ADAPTER_MODULES)[number]['adapterKey'];
