// @generated by scripts/generate-provider-aggregates.mjs; do not edit by hand.
import type { ProviderDefinition, ProviderDefinitionLeaf } from './schemas/provider-definition.js';
import { hydrateProviderDefinitions } from './provider-identity.js';
import { providerDefinition as anthropicProviderDefinition } from './providers/anthropic/definition.js';
import { providerDefinition as codexCliProviderDefinition } from './providers/codex-cli/definition.js';
import { providerDefinition as deepinfraProviderDefinition } from './providers/deepinfra/definition.js';
import { providerDefinition as githubCopilotCliProviderDefinition } from './providers/github-copilot-cli/definition.js';
import { providerDefinition as groqProviderDefinition } from './providers/groq/definition.js';
import { providerDefinition as llamaCppProviderDefinition } from './providers/llama-cpp/definition.js';
import { providerDefinition as moonshotProviderDefinition } from './providers/moonshot/definition.js';
import { providerDefinition as ollamaProviderDefinition } from './providers/ollama/definition.js';
import { providerDefinition as openaiProviderDefinition } from './providers/openai/definition.js';
import { providerDefinition as openclawProviderDefinition } from './providers/openclaw/definition.js';
import { providerDefinition as openrouterProviderDefinition } from './providers/openrouter/definition.js';
import { providerDefinition as perplexityProviderDefinition } from './providers/perplexity/definition.js';

export * from './schemas/provider-definition.js';

const PROVIDER_DEFINITION_LEAVES = [
  anthropicProviderDefinition,
  codexCliProviderDefinition,
  deepinfraProviderDefinition,
  githubCopilotCliProviderDefinition,
  groqProviderDefinition,
  llamaCppProviderDefinition,
  moonshotProviderDefinition,
  ollamaProviderDefinition,
  openaiProviderDefinition,
  openclawProviderDefinition,
  openrouterProviderDefinition,
  perplexityProviderDefinition,
] as const satisfies readonly ProviderDefinitionLeaf[];

export const PROVIDER_DEFINITIONS = hydrateProviderDefinitions(PROVIDER_DEFINITION_LEAVES);

export type ProviderVendorKey = (typeof PROVIDER_DEFINITION_LEAVES)[number]['vendorKey'];
export type BootstrapProviderKey = ProviderVendorKey;

export function resolveProviderDefinition(vendorKey: ProviderVendorKey): ProviderDefinition {
  const definition = PROVIDER_DEFINITIONS.find(
    (candidate) => candidate.vendorKey === vendorKey,
  );
  if (!definition) {
    throw new Error(`Provider definition is missing for vendor key '${vendorKey}'`);
  }
  return definition;
}
