// @generated by scripts/generate-provider-aggregates.mjs; do not edit by hand.
import type { ProviderFactoryModule } from './schemas/provider-factory.js';
import { providerFactory as anthropicProviderFactory } from './providers/anthropic/provider.js';
import { providerFactory as codexCliProviderFactory } from './providers/codex-cli/provider.js';
import { providerFactory as githubCopilotCliProviderFactory } from './providers/github-copilot-cli/provider.js';
import { providerFactory as groqProviderFactory } from './providers/groq/provider.js';
import { providerFactory as llamaCppProviderFactory } from './providers/llama-cpp/provider.js';
import { providerFactory as ollamaProviderFactory } from './providers/ollama/provider.js';
import { providerFactory as openaiProviderFactory } from './providers/openai/provider.js';
import { providerFactory as vllmProviderFactory } from './providers/vllm/provider.js';

export * from './schemas/provider-factory.js';

export const CERTIFIED_PROVIDER_FACTORIES = [
  anthropicProviderFactory,
  codexCliProviderFactory,
  githubCopilotCliProviderFactory,
  groqProviderFactory,
  llamaCppProviderFactory,
  ollamaProviderFactory,
  openaiProviderFactory,
  vllmProviderFactory,
] as const satisfies readonly ProviderFactoryModule[];

export type CertifiedProviderFactoryVendorKey =
  (typeof CERTIFIED_PROVIDER_FACTORIES)[number]['vendorKey'];

const PROVIDER_FACTORY_BY_VENDOR: ReadonlyMap<string, ProviderFactoryModule> = new Map(
  CERTIFIED_PROVIDER_FACTORIES.map((factory) => [
    factory.vendorKey,
    factory,
  ]),
);

export function resolveProviderFactory(vendorKey: string): ProviderFactoryModule | undefined {
  return PROVIDER_FACTORY_BY_VENDOR.get(vendorKey);
}
