// @generated by scripts/generate-provider-aggregates.mjs; do not edit by hand.
import type { ProviderAdapterModule } from './schemas/provider-adapter.js';
import { providerAdapter as anthropicProviderAdapter } from './providers/anthropic/adapter.js';
import { providerAdapter as codexCliProviderAdapter } from './providers/codex-cli/adapter.js';
import { providerAdapter as githubCopilotCliProviderAdapter } from './providers/github-copilot-cli/adapter.js';
import { providerAdapter as groqProviderAdapter } from './providers/groq/adapter.js';
import { providerAdapter as llamaCppProviderAdapter } from './providers/llama-cpp/adapter.js';
import { providerAdapter as ollamaProviderAdapter } from './providers/ollama/adapter.js';
import { providerAdapter as openaiProviderAdapter } from './providers/openai/adapter.js';
import { providerAdapter as qwenCodeProviderAdapter } from './providers/qwen-code/adapter.js';

export * from './schemas/provider-adapter.js';
export { providerAdapter as anthropicAdapter, createAnthropicAdapter } from './providers/anthropic/adapter.js';
export { providerAdapter as codexCliAdapter, CODEX_CLI_EXECUTION_CAPABILITY_PROFILE, createCodexCliAdapter, renderCodexCliPrompt } from './providers/codex-cli/adapter.js';
export { providerAdapter as githubCopilotCliAdapter } from './providers/github-copilot-cli/adapter.js';
export { providerAdapter as groqAdapter } from './providers/groq/adapter.js';
export { providerAdapter as llamaCppAdapter } from './providers/llama-cpp/adapter.js';
export { providerAdapter as ollamaAdapter, createOllamaAdapter, isToolCapableModel } from './providers/ollama/adapter.js';
export { providerAdapter as openaiAdapter, createChatCompletionsAdapter } from './providers/openai/adapter.js';
export { providerAdapter as qwenCodeAdapter, QWEN_CODE_EXECUTION_CAPABILITY_PROFILE, createQwenCodeAdapter, renderQwenCodePrompt } from './providers/qwen-code/adapter.js';

export const CERTIFIED_PROVIDER_ADAPTER_MODULES = [
  anthropicProviderAdapter,
  codexCliProviderAdapter,
  githubCopilotCliProviderAdapter,
  groqProviderAdapter,
  llamaCppProviderAdapter,
  ollamaProviderAdapter,
  openaiProviderAdapter,
  qwenCodeProviderAdapter,
] as const satisfies readonly ProviderAdapterModule[];

export type CertifiedProviderAdapterKey =
  (typeof CERTIFIED_PROVIDER_ADAPTER_MODULES)[number]['adapterKey'];
