// @generated by scripts/generate-provider-aggregates.mjs; do not edit by hand.
import type { ProviderFactoryModule } from './schemas/provider-factory.js';
import { providerFactory as anthropicProviderFactory } from './providers/anthropic/provider.js';
import { providerFactory as codexCliProviderFactory } from './providers/codex-cli/provider.js';
import { providerFactory as deepinfraProviderFactory } from './providers/deepinfra/provider.js';
import { providerFactory as githubCopilotCliProviderFactory } from './providers/github-copilot-cli/provider.js';
import { providerFactory as groqProviderFactory } from './providers/groq/provider.js';
import { providerFactory as huggingfaceTgiProviderFactory } from './providers/huggingface-tgi/provider.js';
import { providerFactory as llamaCppProviderFactory } from './providers/llama-cpp/provider.js';
import { providerFactory as moonshotProviderFactory } from './providers/moonshot/provider.js';
import { providerFactory as ollamaProviderFactory } from './providers/ollama/provider.js';
import { providerFactory as openaiProviderFactory } from './providers/openai/provider.js';
import { providerFactory as qwenCodeProviderFactory } from './providers/qwen-code/provider.js';
import { providerFactory as openclawProviderFactory } from './providers/openclaw/provider.js';
import { providerFactory as openrouterProviderFactory } from './providers/openrouter/provider.js';
import { providerFactory as perplexityProviderFactory } from './providers/perplexity/provider.js';
import { providerFactory as vllmProviderFactory } from './providers/vllm/provider.js';

export * from './schemas/provider-factory.js';

export const CERTIFIED_PROVIDER_FACTORIES = [
  anthropicProviderFactory,
  codexCliProviderFactory,
  deepinfraProviderFactory,
  githubCopilotCliProviderFactory,
  groqProviderFactory,
  huggingfaceTgiProviderFactory,
  llamaCppProviderFactory,
  moonshotProviderFactory,
  ollamaProviderFactory,
  openaiProviderFactory,
  qwenCodeProviderFactory,
  openclawProviderFactory,
  openrouterProviderFactory,
  perplexityProviderFactory,
  vllmProviderFactory,
] as const satisfies readonly ProviderFactoryModule[];

export type CertifiedProviderFactoryVendorKey =
  (typeof CERTIFIED_PROVIDER_FACTORIES)[number]['vendorKey'];

const PROVIDER_FACTORY_BY_VENDOR: ReadonlyMap<string, ProviderFactoryModule> = new Map(
  CERTIFIED_PROVIDER_FACTORIES.map((factory) => [
    factory.vendorKey,
    factory,
  ]),
);

export function resolveProviderFactory(vendorKey: string): ProviderFactoryModule | undefined {
  return PROVIDER_FACTORY_BY_VENDOR.get(vendorKey);
}
